### ISSUE TITLE
Grunt child tasks output not being recorded

### ISSUE THREAD

**Issue by JaKXz** [brutaldev/logfile-grunt#1]
![screen shot 2014-04-04 at 3 10 09 pm](https://cloud.githubusercontent.com/assets/2642545/2619246/d479fd0e-bc2c-11e3-8616-445e4de8b8e7.png)
I followed the instructions to get the most basic logging (i.e. `require('logfile-grunt')(grunt);` with my other Gruntfile dependencies) but I'm not seeing the console output in the log file (see screenshot). 

Am I missing something?

**Comment by brutaldev** [comment]
The messages that are missing from the log come from Express or another application that was spawned. The plugin only hijacks messages from Grunt which is typically task output and so forth. External applications that are launched by Grunt (such as an Express server) may write message to the console differently and will not be intercepted and written to file.

That being said, I do want to take the time to see if this can be solved because concurrent tasks, for example, also do not have their output captured for the same reason. There should be a way to capture the output of any processes spawned by Grunt, just need to figure it out...

**Comment by lxlang** [comment]
:+1: 
i woulr realyl like to have this feature.
now every childtask spawned by grunt-concurrent gets his own logfile. So all my output is captured, but ist a pain in the a*\* to read this.
If i find a proper solution for this, i will opem a PR!

**Comment by gang-qiu** [comment]
+1 would like this feature very much

**Comment by brutaldev** [comment]
These issues should be corrected now in v0.2.0.
Please refer to the [Using Concurrent and Parallelize](https://github.com/brutaldev/logfile-grunt#using-concurrent-and-parallelize) section on how to configure the logger to play nice with concurrent tasks.
